[CmdletBinding()]
param(
    [string]$RG,
    [string]$LOCATION,
    [string]$FOUNDRY_NAME,
    [string]$PROJECT_NAME,
    [string]$DEPLOYMENT_NAME,
    [switch]$WhatIfOnly,
    [switch]$NoWriteEnv
)

$ErrorActionPreference = 'Stop'

Write-Host "[deploy.ps1] Starting Azure deployment..."
Write-Host "[deploy.ps1] This can take ~3-5 minutes before output is printed. Please wait..."

function Get-DefaultedValue {
    param(
        [string]$Provided,
        [string]$EnvValue,
        [string]$DefaultValue
    )

    if (-not [string]::IsNullOrWhiteSpace($Provided)) { return $Provided }
    if (-not [string]::IsNullOrWhiteSpace($EnvValue)) { return $EnvValue }
    return $DefaultValue
}

function Assert-CommandExists {
    param([string]$Name)

    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command '$Name' was not found in PATH. Install it and try again."
    }
}

function Write-DotEnvFile {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [hashtable]$Values,

        [string[]]$NoOverwriteKeys = @(),

        [string[]]$RemoveKeys = @()
    )

    $existingLines = @()
    if (Test-Path -LiteralPath $Path) {
        $existingLines = Get-Content -LiteralPath $Path -ErrorAction Stop
    }

    $keysToUpdate = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach ($k in $Values.Keys) { [void]$keysToUpdate.Add([string]$k) }

    $noOverwrite = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach ($k in $NoOverwriteKeys) { [void]$noOverwrite.Add([string]$k) }

    $removeKeys = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    foreach ($k in $RemoveKeys) { [void]$removeKeys.Add([string]$k) }

    $existingKeys = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)

    $outputLines = @()

    foreach ($line in $existingLines) {
        $m = [regex]::Match($line, '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=')
        if ($m.Success) {
            $key = $m.Groups[1].Value
            [void]$existingKeys.Add($key)

            # Remove keys entirely if requested.
            if ($removeKeys.Contains($key)) {
                continue
            }

            # For keys we want to preserve (e.g., user-entered SQL creds), keep existing lines.
            if ($keysToUpdate.Contains($key) -and $noOverwrite.Contains($key)) {
                $outputLines += $line
                continue
            }

            # For keys we're updating, remove existing lines to avoid duplicates.
            if ($keysToUpdate.Contains($key)) {
                continue
            }
        }

        $outputLines += $line
    }

    if ($outputLines.Count -gt 0 -and ($outputLines[-1] -ne '')) {
        $outputLines += ''
    }

    $outputLines += '# ---- Generated by deploy.ps1 ----'
    foreach ($k in ($Values.Keys | Sort-Object)) {
        if ($noOverwrite.Contains([string]$k) -and $existingKeys.Contains([string]$k)) {
            continue
        }
        $v = [string]$Values[$k]
        $outputLines += ("{0}={1}" -f $k, $v)
    }

    Set-Content -LiteralPath $Path -Value $outputLines -Encoding utf8 -NoNewline:$false
}

Assert-CommandExists -Name 'az'

$RG = Get-DefaultedValue -Provided $RG -EnvValue $env:RG -DefaultValue 'rg-foundry-demo'
$LOCATION = Get-DefaultedValue -Provided $LOCATION -EnvValue $env:LOCATION -DefaultValue 'eastus2'

$defaultFoundryName = ("fdry{0}{1}" -f (Get-Random -Minimum 1000 -Maximum 9999), (Get-Random -Minimum 1000 -Maximum 9999))
$FOUNDRY_NAME = Get-DefaultedValue -Provided $FOUNDRY_NAME -EnvValue $env:FOUNDRY_NAME -DefaultValue $defaultFoundryName

$defaultProjectName = ("proj{0}" -f (Get-Random -Minimum 1000 -Maximum 9999))
$PROJECT_NAME = Get-DefaultedValue -Provided $PROJECT_NAME -EnvValue $env:PROJECT_NAME -DefaultValue $defaultProjectName

$DEPLOYMENT_NAME = Get-DefaultedValue -Provided $DEPLOYMENT_NAME -EnvValue $env:DEPLOYMENT_NAME -DefaultValue 'gpt5mini'

$deploymentId = ("foundryDeploy-{0}" -f (Get-Random -Minimum 10000 -Maximum 99999))

Write-Host "[deploy.ps1] Resource group: $RG"
Write-Host "[deploy.ps1] Location: $LOCATION"
Write-Host "[deploy.ps1] Deployment name: $deploymentId"
Write-Host ""

# Create (or update) the resource group
az group create -n $RG -l $LOCATION --only-show-errors | Out-Null

if ($WhatIfOnly) {
    az deployment group what-if `
        -g $RG `
        -n $deploymentId `
        -f main.bicep `
        -p location=$LOCATION `
           foundryName=$FOUNDRY_NAME `
           projectName=$PROJECT_NAME `
           deploymentName=$DEPLOYMENT_NAME
    return
}

# Deploy Bicep template
az deployment group create `
    -g $RG `
    -n $deploymentId `
    -f main.bicep `
    -p location=$LOCATION `
       foundryName=$FOUNDRY_NAME `
       projectName=$PROJECT_NAME `
       deploymentName=$DEPLOYMENT_NAME `
    --only-show-errors | Out-Null

$subId = az account show --query id -o tsv

$foundryId = az deployment group show -g $RG -n $deploymentId --query properties.outputs.foundryInstanceId.value -o tsv
$projectId = az deployment group show -g $RG -n $deploymentId --query properties.outputs.foundryProjectId.value -o tsv
$modelDeployName = az deployment group show -g $RG -n $deploymentId --query properties.outputs.modelDeploymentName.value -o tsv
$modelDeployId = az deployment group show -g $RG -n $deploymentId --query properties.outputs.modelDeploymentId.value -o tsv
$foundryEndpoint = az deployment group show -g $RG -n $deploymentId --query properties.outputs.foundryEndpoint.value -o tsv

$disableLocalAuth = ''
try {
    $disableLocalAuth = az cognitiveservices account show -g $RG -n $FOUNDRY_NAME --query properties.disableLocalAuth -o tsv --only-show-errors
} catch {
    $disableLocalAuth = ''
}

$isKeyAuthDisabled = $false
if (-not [string]::IsNullOrWhiteSpace($disableLocalAuth)) {
    $isKeyAuthDisabled = ($disableLocalAuth.ToString().ToLowerInvariant() -eq 'true')
}

$foundryApiKey = ''
try {
    # Requires local auth enabled (main.bicep sets disableLocalAuth: false)
    if (-not $isKeyAuthDisabled) {
        $foundryApiKey = az cognitiveservices account keys list -g $RG -n $FOUNDRY_NAME --query key1 -o tsv --only-show-errors
    }
} catch {
    $foundryApiKey = ''
}

if ($isKeyAuthDisabled) {
    Write-Host "[deploy.ps1] Note: Key-based authentication is DISABLED for this Foundry account (disableLocalAuth=true)."
    Write-Host "[deploy.ps1] The Python client MUST use Entra (Azure AD) auth via AzureCliCredential/Managed Identity."
    Write-Host "[deploy.ps1] Ensure AZURE_OPENAI_API_KEY is NOT set (in .env or your machine environment)."
    Write-Host ""
} elseif ([string]::IsNullOrWhiteSpace($foundryApiKey)) {
    Write-Host "[deploy.ps1] Warning: Could not retrieve an API key for '$FOUNDRY_NAME'."
    Write-Host "[deploy.ps1] If Azure AD auth isn't working on this machine, set AZURE_OPENAI_API_KEY manually or re-run after ensuring local auth is enabled."
    Write-Host ""
}

Write-Host ""
Write-Host "### Paste into your .env ###"
Write-Host "AZURE_SUBSCRIPTION_ID=$subId"
Write-Host "FOUNDRY_INSTANCE_ID=$foundryId"
Write-Host "FOUNDRY_PROJECT_ID=$projectId"
Write-Host "MODEL_DEPLOYMENT_NAME=$modelDeployName"
Write-Host "MODEL_DEPLOYMENT_ID=$modelDeployId"
Write-Host "FOUNDRY_ENDPOINT=$foundryEndpoint"

Write-Host ""
Write-Host "### Agent Framework / Azure OpenAI-compatible vars (recommended) ###"
Write-Host "# Copy these into your .env as well"
Write-Host "AZURE_OPENAI_ENDPOINT=$foundryEndpoint"
Write-Host "AZURE_OPENAI_CHAT_DEPLOYMENT_NAME=$modelDeployName"

if (-not $isKeyAuthDisabled -and -not [string]::IsNullOrWhiteSpace($foundryApiKey)) {
    Write-Host "AZURE_OPENAI_API_KEY=$foundryApiKey"
}

Write-Host ""
Write-Host "### Azure SQL placeholders (fill these in later) ###"
Write-Host "# Copy these into your .env if you plan to connect to Azure SQL"
Write-Host "SQL_SERVER="
Write-Host "SQL_DATABASE="
Write-Host "SQL_USERNAME="
Write-Host "SQL_PASSWORD="

if (-not $NoWriteEnv) {
    $envPath = Join-Path $PSScriptRoot '.env'
    $envVars = @{
        AZURE_SUBSCRIPTION_ID = $subId
        FOUNDRY_INSTANCE_ID = $foundryId
        FOUNDRY_PROJECT_ID = $projectId
        MODEL_DEPLOYMENT_NAME = $modelDeployName
        MODEL_DEPLOYMENT_ID = $modelDeployId
        FOUNDRY_ENDPOINT = $foundryEndpoint
        AZURE_OPENAI_ENDPOINT = $foundryEndpoint
        AZURE_OPENAI_CHAT_DEPLOYMENT_NAME = $modelDeployName
        SQL_SERVER = ''
        SQL_DATABASE = ''
        SQL_USERNAME = ''
        SQL_PASSWORD = ''
    }

    if (-not $isKeyAuthDisabled -and -not [string]::IsNullOrWhiteSpace($foundryApiKey)) {
        $envVars['AZURE_OPENAI_API_KEY'] = $foundryApiKey
    }

    $removeKeys = @()
    if ($isKeyAuthDisabled) {
        $removeKeys = @('AZURE_OPENAI_API_KEY')
    }

    Write-DotEnvFile -Path $envPath -Values $envVars -NoOverwriteKeys @('SQL_SERVER','SQL_DATABASE','SQL_USERNAME','SQL_PASSWORD') -RemoveKeys $removeKeys
    Write-Host ""
    Write-Host "[deploy.ps1] Wrote/updated .env at: $envPath"
    Write-Host "[deploy.ps1] Re-run: uv run main.py"
}